### ISSUE TITLE
Unicode in API

### ISSUE THREAD

**Issue by agran** [Qoracoin/Qora#8]
[COMMAND] POST namepayment {"amount":"1.0","fee":"1.0","sender":"QfaucettiqGtTe1yXVHgZETfrFJ4bBmSoX","recipient":"олег"}
[RESULT] {
   "error":701,
   "message":"The name is not registered"
}

debug gives:
String nameName = ���� (

JSONObject jsonObject1 = (JSONObject) JSONValue.parse("{\"recipient\":\"олег\"}");
String nameName = (String) jsonObject1.get("recipient");
works well

**Comment by rhartness** [comment]
I have a similar issue (might be related, might not.)

I tried to run the new 0.20.0 on my machine work machine (with a corporate AD account) and I'm getting the following error (slightly modified):

`java.io.IOException: Parent folder does not exist: C:\Users?##\AppData\Roaming\Qora\data\data.dat`

If you will notice, a portion of the Users path string has been replaced with a `?`.  This is because my User folder begins with a lower-cased U, followed by 6 digits.

Currently, I can't run Qora because of this bug.  I know this is a minor issue-- how many users have computer accounts with `\u####` in the string, but it is effecting at least one person. 

:raises hand:

**Comment by vbecas** [comment]
You can instead of installing the .exe download the .zip version, extract it in C:/ or somewhere that you dont have that issue and double click on run.bat

**Comment by agran** [comment]
Try set params in C:\Program Files (x86)\Qora\settings.json 
"datadir": "C:\Users\name\AppData\Roaming\Qora\data",
 "walletdir" : "C:\Users\name\AppData\Roaming\Qora\wallet"

**Comment by rhartness** [comment]
Thanks Agran!  Change the name to use UPPERCASE U in the settings file fixed it.

**Comment by xloem** [comment]
> [COMMAND] POST namepayment {"amount":"1.0","fee":"1.0","sender":"QfaucettiqGtTe1yXVHgZETfrFJ4bBmSoX","recipient":"олег"}
> [RESULT] {
> "error":701,
> "message":"The name is not registered"
> }
@agran, I just tried this on 0.24.0 both in the graphical console and using curl from the commandline on 64-bit gentoo linux, LANG=en_US.UTF-8 , and it worked fine !

**Comment by agran** [comment]
I have already fixed this bug.
https://github.com/Qoracoin/Qora/commit/5271543a40f43ffaef5ea2633263a31a1876c810
